### PR TITLE
Bump pulldown-cmark to 0.5

### PR DESCRIPTION
**Pull request by eclipseo**
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>

### CODE REVIEW

**Comment by eclipseo** [comment]
get_offset is deprecated too, but it' above my skill to upgrade it:

> the get_offset method on the parser was removed. Its semantics were poorly defined and only provided users with the start offset of the next event. To get proper source mapping information which includes the entire source range for each event, upgrade the Parser to an OffsetIter using the into_offset_iter method. This produces an iterator over (Event, Range<usize>) tuples.

Can you help updating it?

**Comment by igor-raits** [comment]
@budziq @GuillaumeGomez ping?

**Comment by GuillaumeGomez** [comment]
Who dares \*summon\* me in here?

**Comment by GuillaumeGomez** [comment]
But more seriously: why was I pinged?

**Comment by igor-raits** [comment]
@GuillaumeGomez whoops, I just noticed that you were the author of the patch and not committer. sorry :/

**Comment by GuillaumeGomez** [comment]
No problem, good luck. ;)

**Comment by igor-raits** [comment]
ping @budziq

**Comment by djc** [comment]
Closing this in favor of #126, thanks for the contribution!

**Pull request closed without merging**
