### PR TITLE
Get rlib hash from parent path of json in fingerprint

### LINKED ISSUE #120: E0464 in nightly
The rust cookbook started seeing E0464 on nightly.  Has anyone else seen this?

https://github.com/rust-lang-nursery/rust-cookbook/issues/590

### PR DESCRIPTION
**Pull request by AndyGauge**
Fixes #120

### CODE REVIEW

**Comment by AndyGauge** [comment]
current rust nightly no longer allows extern crates in markdown.  This pull request addresses the changes to the compiler internals which removed the hash from the json file's name.

**Comment by mitchmindtree** [comment]
Can confirm, recently all of the [nannou guide](https://guide.nannou.cc/) [tests](https://github.com/nannou-org/nannou/tree/master/guide/book_tests) began [failing](https://github.com/nannou-org/nannou/pull/636/checks?check_run_id=920796725), however switching our skeptic dependency over to this branch resolves our issues.

Thanks @AndyGauge!

**Comment by AndyGauge** [comment]
This is how the rust cookbook is doing it in case anyone else has the need before this is merged:
```
skeptic = { git = 'https://github.com/andygauge/rust-skeptic'}
```

**Comment by djc** [comment]
Thanks for your contribution!

**Pull request merged**
