### PR TITLE
Add license files and use https in README.md links

### LINKED ISSUE #94: cargo_metadata v0.7
It would be huge help if you would be able to port skeptic to cargo_metadata 0.7.x.

Thanks!

### PR DESCRIPTION
**Pull request by budziq**
closes #94

### CODE REVIEW

**Comment by igor-raits** [comment]
@budziq thanks, can you also put them into `src/skeptic`? Either copy them there or make symlinks. Otherwise when you will publish next version of `skeptic`, it won't appear on crates.io.

**Comment by budziq** [comment]
Hi @ignatenkobrain,

I'm not sure what do you mean by 

>  it won't appear on crates.io

Information about license was already available in crates.io prior to this change. And I have problem understanding why would anyone want to have license files in the src directory.

Could you explain in more detail or point me to an exemplary crates.io package that is setup according to your needs?

**Comment by igor-raits** [comment]
For example, https://github.com/rayon-rs/rayon (see rayon-core and rayon-futures directories). In rayon, files are copied. In other projects, most of the people just symlink those files.

**Comment by budziq** [comment]
Hmm I'll do it. But You've picked my interest at 

> it won't appear on crates.io

could you explain further? Do you mean that your license actually requires for the license files to be downloaded along with the source code during the build time? Or is it something to do with how the crate is displayed in the crates.io website?

**Comment by igor-raits** [comment]
> could you explain further? Do you mean that your license actually requires for the license files to be downloaded along with the source code during the build time? Or is it something to do with how the crate is displayed in the crates.io website?

Sure. When you run `cargo publish`, it takes current snapshot of files and uploads it in archive to crates.io. Then Linux distribution packagers take that file and package for their distribution. So they need to have those licenses there.

Another case when somebody does `cargo vendor` to vendor all dependencies, it downloads all archives from crates.io and unpacks into one directory. So if you ever want to go through your dependencies and review their licenses, they need to be there.

**Comment by budziq** [comment]
I hope https://github.com/budziq/rust-skeptic/pull/98 solves the problem :)

**Comment by igor-raits** [comment]
Yup, seems good. Thanks a lot!

**Pull request merged**
