### PR TITLE
Print additional information when a command fails to execute

### PR DESCRIPTION
**Pull request by Marwes**
May give some additional insight to the spurious failures in issue #9.

### CODE REVIEW

**Comment by brson** [comment]
I'm so sorry it took so long to get to this. Thank you @Marwes!

**Comment by Marwes** [comment]
No worries! Lets hope this can shine some light on the failures!

**Comment by brson** [comment]
Still have a todo on my list to publish this in a new rev.

**Comment by Marwes** [comment]
No hurry, realized I could just make a new branch which pulls skeptic from git and then run travis until I got an error. Unfortunately the extra information didn't point to any errors as far as I can tell (see #9)

**Pull request merged**
