### PR TITLE
Tempfile

### PR DESCRIPTION
**Pull request by budziq**

### CODE REVIEW

**Comment by cristicbz** [comment]
Hi @budziq thanks so much for this great library! Is this PR blocked on anything?

Our CI is set up to fail on rust-sec advisories and the dependency to the deprecated `tempdir` is causing our build to fail. We can temporarily ignore the warning of course, but I came here to create a PR to switch to tempfile and then noticed there's one already. Is there some way I could help to get this merged?

**Comment by fosskers** [comment]
Coming here to report a dependency chain that injects an old version of `rand` into `ggez` via:
```
ggez 0.5.1 -> skeptic 0.13 -> tempdir 0.3 -> rand 0.4.6
```
If this PR could be merged, other bounds be bumped, and a release made, a number of upstream crates would benefit. Please and thanks!

**Comment by mimi89999** [comment]
I guess that https://github.com/budziq/rust-skeptic/pull/110 can be closed now.

**Comment by djc** [comment]
Thanks for fixing this up!

**Pull request merged**
